parameters:
    #Set up the email template defaults
    savvy_contact.notification_template:      SavvyContactBundle:Email:notification.html.twig
    savvy_contact.confirmation_template:      SavvyContactBundle:Email:confirmation.html.twig
    #Full namespace for contact form to be used
    savvy_contact.formtype.namespace: "\Savvy\ContactBundle\Form\ContactType"